apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-resume-analyser.fullname" . }}-api
  namespace: {{ include "ai-resume-analyser.namespace" . }}
  labels:
    {{- include "ai-resume-analyser.componentLabels" (dict "component" "api" "root" .) | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    {{- include "ai-resume-analyser.componentSelectorLabels" (dict "component" "api" "root" .) | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
