apiVersion: v1
kind: Namespace
metadata:
  name: resume-analyser
  labels:
    app.kubernetes.io/part-of: ai-resume-analyser
    app.kubernetes.io/managed-by: kustomize
    # Enable AWS Load Balancer Controller target group binding discovery
    elbv2.k8s.aws/pod-readiness-gate-inject: enabled
